tmp

diff --git a/.github/workflows/experimental.yml b/.github/workflows/experimental.yml
--- a/.github/workflows/experimental.yml
+++ b/.github/workflows/experimental.yml
@@ -21,7 +21,24 @@ jobs:
         run: echo "$GITHUB_CONTEXT"
       - name: Compute release number
         run: |
-          LATEST_TAG=`git describe --tags --always | cut -d'-' -f1 | tr -d v` # git describe will fail if there are no tags yet
+          git describe --tags --always # git describe fails if there are no tags yet
+          retVal=$?
+          if [ $retVal -ne 0 ]; then
+            echo "No last tag detected, try to assign 0.0.0"
+            tag="0.0.0"
+            if git rev-parse -q --verify "refs/tags/$tag" >/dev/null; then
+              echo "tag $tag already exists, aborting"
+              exit 1
+            else
+              echo "creating tag $tag"
+              echo "VERSION=$tag" >> $GITHUB_ENV
+              echo "VERSION=$tag"
+            fi
+            exit 0
+          fi
+
+          LATEST_TAG=`git describe --tags --always | cut -d'-' -f1 | tr -d v`
+          echo "LATEST_TAG=$LATEST_TAG"
           MAJOR=`echo $LATEST_TAG | cut -d'.' -f1`
           MINOR=`echo $LATEST_TAG | cut -d'.' -f2`
           PATCH=`echo $LATEST_TAG | cut -d'.' -f3`
@@ -47,18 +64,6 @@ jobs:
           esac
           echo "VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV
           echo "VERSION=$MAJOR.$MINOR.$PATCH"
-      - name: Create first tag
-        if: ${{ failure() }}
-        run:  |
-          tag="0.0.0"
-          if git rev-parse -q --verify "refs/tags/$tag" >/dev/null; then
-            echo "tag $tag already exists, aborting"
-            exit 1
-          else
-            echo "creating tag $tag"
-            echo "VERSION=$tag" >> $GITHUB_ENV
-            echo "VERSION=$tag"
-          fi
       - name: Write version to file
         uses: brettdorrans/write-version-to-file@master
         with:
