implement fallback

diff --git a/.github/workflows/experimental.yml b/.github/workflows/experimental.yml
--- a/.github/workflows/experimental.yml
+++ b/.github/workflows/experimental.yml
@@ -22,22 +22,7 @@ jobs:
       - name: Compute release number
         continue-on-error: true
         run: |
-          git describe --tags # git describe fails if there are no tags yet
-          retVal=$?
-          if [ $retVal -ne 0 ]; then
-            echo "No last tag detected, try to assign 0.0.0"
-            tag="0.0.0"
-            if git rev-parse -q --verify "refs/tags/$tag" >/dev/null; then
-              echo "tag $tag already exists, aborting"
-              exit 1
-            else
-              echo "creating tag $tag"
-              echo "VERSION=$tag" >> $GITHUB_ENV
-              echo "VERSION=$tag"
-              touch .VERSION
-            fi
-            exit 0
-          fi
+          git describe --tags # git describe fails if there are no tags yet. Required to fail the step.
 
           LATEST_TAG=`git describe --tags | cut -d'-' -f1 | tr -d v`
           echo "LATEST_TAG=$LATEST_TAG"
@@ -66,6 +51,21 @@ jobs:
           esac
           echo "VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV
           echo "VERSION=$MAJOR.$MINOR.$PATCH"
+
+      - name: Fallback set version
+        if: failure()
+        run: |
+          tag="0.0.0"
+          echo "No last tag detected, try to assign $tag"
+          if git rev-parse -q --verify "refs/tags/$tag" >/dev/null; then
+            echo "tag $tag already exists, aborting"
+            exit 1
+          else
+            echo "creating tag $tag"
+            echo "VERSION=$tag" >> $GITHUB_ENV
+            echo "VERSION=$tag"
+            touch .VERSION
+          fi
       - name: Write version to file
         uses: brettdorrans/write-version-to-file@master
         with:
